@Order.API_HostAddress = http://localhost:5068

GET {{Order.API_HostAddress}}/api/products
Content-Type: application/json

###
POST {{Order.API_HostAddress}}/api/Products/CreateCategory
Content-Type: application/json
{
  "name": "kalemler"
}
###
POST {{Order.API_HostAddress}}/api/products
Content-Type: application/json
{
  "name": "Kalem 3",
  "Quantity" : 20,
  "price": 20,
  "categoryId": 1
}




